- build.gradle
- src/main/java/com/hyun/bookmarkshare/config/SwaggerConfig.java
- src/main/java/com/hyun/bookmarkshare/exceptions/CustomExceptionHandler.java
- src/main/java/com/hyun/bookmarkshare/manage/bookmark/controller/BookmarkRestController.java
- src/main/java/com/hyun/bookmarkshare/manage/bookmark/service/BookmarkService.java
- src/main/java/com/hyun/bookmarkshare/manage/bookmark/service/BookmarkServiceImpl.java
- src/main/java/com/hyun/bookmarkshare/manage/folder/controller/FolderRestController.java
- src/main/java/com/hyun/bookmarkshare/manage/folder/controller/dto/FolderListRequestDto.java
- src/main/java/com/hyun/bookmarkshare/manage/folder/controller/dto/FolderReorderRequestDto.java
- src/main/java/com/hyun/bookmarkshare/manage/folder/controller/dto/FolderReorderResponseEntity.java
- src/main/java/com/hyun/bookmarkshare/manage/folder/controller/dto/FolderRequestDto.java
- src/main/java/com/hyun/bookmarkshare/manage/folder/controller/dto/FolderResponseEntity.java
- src/main/java/com/hyun/bookmarkshare/manage/folder/dao/FolderRepository.java
- src/main/java/com/hyun/bookmarkshare/manage/folder/entity/Folder.java
- src/main/java/com/hyun/bookmarkshare/manage/folder/exceptions/FolderExceptionErrorCode.java
- src/main/java/com/hyun/bookmarkshare/manage/folder/service/FolderRequestValidator.java
- src/main/java/com/hyun/bookmarkshare/manage/folder/service/FolderService.java
- src/main/java/com/hyun/bookmarkshare/manage/folder/service/FolderServiceImpl.java
- src/main/java/com/hyun/bookmarkshare/user/dao/UserRepository.java
- src/main/java/com/hyun/bookmarkshare/user/service/LoginServiceImpl.java
- src/main/resources/mapper/FolderMapper.xml
- src/main/resources/mapper/LoginMapper.xml
- src/test/java/com/hyun/bookmarkshare/manage/folder/service/FolderRequestValidatorTest.java
- src/test/java/com/hyun/bookmarkshare/manage/folder/service/FolderServiceImplTest.java
- src/test/java/com/hyun/bookmarkshare/user/service/LoginServiceImplTest.java
> chore(backend): Add swagger with change basic url (#1, #2)

- src/main/java/com/hyun/bookmarkshare/manage/folder/controller/FolderRestController.java
- src/main/java/com/hyun/bookmarkshare/manage/folder/controller/dto/FolderCreateRequestDto.java
- src/main/java/com/hyun/bookmarkshare/manage/folder/controller/dto/FolderListRequestDto.java
- src/main/java/com/hyun/bookmarkshare/manage/folder/controller/dto/FolderReorderRequestDto.java
- src/main/java/com/hyun/bookmarkshare/manage/folder/controller/dto/FolderRequestDto.java
- src/main/java/com/hyun/bookmarkshare/manage/folder/dao/FolderRepository.java
- src/main/java/com/hyun/bookmarkshare/manage/folder/service/FolderService.java
- src/main/java/com/hyun/bookmarkshare/manage/folder/service/FolderServiceImpl.java
- src/main/resources/mapper/FolderMapper.xml
- resolve: #4
- 적합한 validation을 위해 폴더 생성 요청 용도의  FolderCreateReqeustDto를 추가.
> feat(folder): Add validation at folder-request-dtos, Add valid at controller (#4)

- build.gradle
- src/main/java/com/hyun/bookmarkshare/manage/folder/controller/dto/FolderListRequestDto.java
- src/main/java/com/hyun/bookmarkshare/manage/folder/controller/dto/FolderRequestDto.java
- src/test/java/com/hyun/bookmarkshare/manage/folder/controller/dto/FolderCreateRequestDtoTest.java
- src/test/java/com/hyun/bookmarkshare/manage/folder/controller/dto/FolderListRequestDtoTest.java
- src/test/java/com/hyun/bookmarkshare/manage/folder/controller/dto/FolderReorderRequestDtoTest.java
- src/test/java/com/hyun/bookmarkshare/manage/folder/controller/dto/FolderRequestDtoTest.java
- resolve: #11 
- Folder 관련 요청 DTO 들의 값 검증에 사용된 validation 어노테이션 단위 테스트 코드 추가.
- Stream 추가 학습 필요성 느낌.
> test(folder): Add folder request dto validation annotation unit test (#11)

- build.gradle
- src/main/java/com/hyun/bookmarkshare/manage/folder/controller/dto/FolderReorderRequestDto.java
- src/main/java/com/hyun/bookmarkshare/manage/folder/controller/dto/FolderRequestDto.java
- src/main/java/com/hyun/bookmarkshare/manage/folder/dao/FolderRepository.java
- src/main/resources/mapper/FolderMapper.xml
- src/test/java/com/hyun/bookmarkshare/manage/folder/dao/FolderRepositoryInsertQueryTest.java
- src/test/java/com/hyun/bookmarkshare/manage/folder/dao/FolderRepositorySelectQueryTest.java
- src/test/java/com/hyun/bookmarkshare/manage/folder/dao/FolderRepositoryUpdateQueryTest.java
- resolve: #7 
- List로 감싸진 Folder의 folderSeq 필드 값들의 순서를 assertThat으로 검증하는 방법을 알게 되었음. Junit5 추가 학습이 필요.
> test(folder): Add folder mapper query unit test (#7)

- src/main/java/com/hyun/bookmarkshare/manage/bookmark/controller/BookmarkRestController.java
- src/main/java/com/hyun/bookmarkshare/manage/bookmark/controller/dto/BookmarkListRequestDto.java
- src/main/java/com/hyun/bookmarkshare/manage/bookmark/controller/dto/BookmarkListResponseEntity.java
- src/main/java/com/hyun/bookmarkshare/manage/bookmark/dao/BookmarkRepository.java
- src/main/java/com/hyun/bookmarkshare/manage/bookmark/entity/Bookmark.java
- src/main/java/com/hyun/bookmarkshare/manage/bookmark/service/BookmarkService.java
- src/main/java/com/hyun/bookmarkshare/manage/bookmark/service/BookmarkServiceImpl.java
- src/main/resources/mapper/BookmarkMapper.xml
- src/test/java/com/hyun/bookmarkshare/manage/bookmark/controller/dto/BookmarkListRequestDtoTest.java
- src/test/java/com/hyun/bookmarkshare/manage/folder/controller/dto/FolderListRequestDtoTest.java
- resolve: #14
- 북마크 리스트 요청 dto 값 검증 테스트 코드 커밋 포함 test(bookmark): Add bookmark-list-request-dto validtaion test
> feat(bookmark): Add bookmark-list flow (#14)

- src/main/java/com/hyun/bookmarkshare/config/SecurityConfig.java
- src/main/java/com/hyun/bookmarkshare/config/WebConfig.java
- src/main/java/com/hyun/bookmarkshare/security/jwt/util/JwtTokenizer.java
- src/main/java/com/hyun/bookmarkshare/user/controller/UserPermitRestController.java
- src/main/java/com/hyun/bookmarkshare/user/controller/UserRestController.java
- src/main/java/com/hyun/bookmarkshare/user/controller/dto/LoginRefreshResponseDto.java
- src/main/java/com/hyun/bookmarkshare/user/controller/dto/LoginResponseDto.java
- src/main/java/com/hyun/bookmarkshare/user/controller/dto/LoginResponseEntity.java
- src/main/java/com/hyun/bookmarkshare/user/controller/dto/RefreshResponseEntity.java
- src/main/java/com/hyun/bookmarkshare/user/dao/UserRepository.java
- src/main/java/com/hyun/bookmarkshare/user/entity/User.java
- src/main/java/com/hyun/bookmarkshare/user/entity/UserRefreshToken.java
- src/main/java/com/hyun/bookmarkshare/user/service/UserService.java
- src/main/java/com/hyun/bookmarkshare/user/service/UserServiceImpl.java
- src/main/resources/mapper/UserMapper.xml
- src/main/resources/static/index.html
- src/main/resources/static/user/loginScript.js
- resolve: #25 
- 테스트 코드 미작성 (추가 필요)
- login, logout 수정 발생.
> feat(user): Add refresh-token flow to extend login state with jwt ref… (#25)

- src/main/java/com/hyun/bookmarkshare/manage/bookmark/controller/BookmarkRestController.java
- src/main/java/com/hyun/bookmarkshare/manage/bookmark/controller/dto/BookmarkReorderRequestDto.java
- src/main/java/com/hyun/bookmarkshare/manage/bookmark/controller/dto/BookmarkReorderResponseEntity.java
- src/main/java/com/hyun/bookmarkshare/manage/bookmark/dao/BookmarkRepository.java
- src/main/java/com/hyun/bookmarkshare/manage/bookmark/service/BookmarkService.java
- src/main/java/com/hyun/bookmarkshare/manage/bookmark/service/BookmarkServiceImpl.java
- src/main/java/com/hyun/bookmarkshare/user/controller/dto/LoginResponseEntity.java
- src/main/java/com/hyun/bookmarkshare/user/dao/UserRepository.java
- src/main/java/com/hyun/bookmarkshare/user/service/UserServiceImpl.java
- src/main/resources/mapper/BookmarkMapper.xml
- src/main/resources/mapper/UserMapper.xml
- src/test/java/com/hyun/bookmarkshare/manage/bookmark/controller/dto/BookmarkListRequestDtoTest.java
- src/test/java/com/hyun/bookmarkshare/manage/bookmark/dao/BookmarkRepositorySelectQueryTest.java
- src/test/java/com/hyun/bookmarkshare/manage/bookmark/dao/BookmarkRepositoryUpdateQueryTest.java
- src/test/java/com/hyun/bookmarkshare/manage/bookmark/service/GetBookmarkListTest.java
- 이슈 #31 해결
- Refactor : Bookmark 도메인 내부 Parent 단어 삭제
- Docs : BookmarkRestController 에 문서화주석 추가
- (작업 내용 및 영향)
- bookmark 도메인에 findAllByUserIdAndFolderParentSeq 에서 Parent 삭제 &rarr; findAllByUserIdAndFolderSeq
- 북마크는 부모폴더 개념이 아닌, 폴더 내부에 속해 있기 때문.
- (리뷰어들에게 하고 싶은 말)
- 없음
> feat(bookmark): Add bookmark order update process (#31)

- .github/ISSUE_TEMPLATE/커스텀-이슈-템플릿.md
Resolves #36
- Commit, PR, Issue 를 위한 형식의 개선이 필요했었음.
- 각 template 을 생성 후 반영.
- 각 Convention 은 Wiki 에 작성 중.
- 추가 의견이 있으신 분 의견 남겨주세요.
- 
---
> Template: Update custom issue template 1.0.1v

- .github/ISSUE_TEMPLATE/커스텀-이슈-템플릿.md
- .gitignore
- build.gradle
- src/main/java/com/hyun/bookmarkshare/manage/bookmark/dao/BookmarkRepository.java
- src/main/java/com/hyun/bookmarkshare/manage/bookmark/entity/Bookmark.java
- src/main/java/com/hyun/bookmarkshare/smtp/service/EmailService.java
- src/main/resources/mapper/BookmarkMapper.xml
- src/test/java/com/hyun/bookmarkshare/manage/bookmark/dao/BookmarkRepositorySelectQueryTest.java
- src/test/java/com/hyun/bookmarkshare/user/UserIntegrationTest.java
Resolves #{없음}
- 개인 계정을 포함한 파일이 main 브랜치의 commit history에 남아있음
- Service 로직에서 필요한 계정은 `@Value` 어노테이션으로 Properties 에서 가져오는 것으로 변경
- Test 과정에서 사용된 계정은 마스킹 처리
- 
- 
---
> !HOTFIX: Delete commit history

- src/main/java/com/hyun/bookmarkshare/manage/bookmark/dao/BookmarkRepository.java
- src/main/java/com/hyun/bookmarkshare/manage/bookmark/service/BookmarkServiceImpl.java
- src/main/java/com/hyun/bookmarkshare/manage/folder/controller/FolderRestController.java
- src/main/java/com/hyun/bookmarkshare/manage/folder/controller/dto/FolderReorderRequestDto.java
- src/main/java/com/hyun/bookmarkshare/manage/folder/dao/FolderRepository.java
- src/main/java/com/hyun/bookmarkshare/manage/folder/entity/Folder.java
- src/main/java/com/hyun/bookmarkshare/manage/folder/service/FolderRequestValidator.java
- src/main/java/com/hyun/bookmarkshare/manage/folder/service/FolderService.java
- src/main/java/com/hyun/bookmarkshare/manage/folder/service/FolderServiceImpl.java
- src/main/java/com/hyun/bookmarkshare/manage/folder/service/request/FolderCreateServiceRequestDto.java
- src/main/java/com/hyun/bookmarkshare/manage/folder/service/request/FolderReorderServiceRequestDto.java
- src/main/resources/mapper/BookmarkMapper.xml
- src/main/resources/mapper/FolderMapper.xml
- src/test/java/com/hyun/bookmarkshare/manage/bookmark/dao/BookmarkRepositoryDeleteQueryTest.java
- src/test/java/com/hyun/bookmarkshare/manage/bookmark/dao/BookmarkRepositoryInsertQueryTest.java
- src/test/java/com/hyun/bookmarkshare/manage/bookmark/dao/BookmarkRepositorySelectQueryTest.java
- src/test/java/com/hyun/bookmarkshare/manage/bookmark/dao/BookmarkRepositoryUpdateQueryTest.java
- src/test/java/com/hyun/bookmarkshare/manage/folder/controller/dto/FolderReorderRequestDtoTest.java
- src/test/java/com/hyun/bookmarkshare/manage/folder/dao/FolderRepositoryDeleteQueryTest.java
- src/test/java/com/hyun/bookmarkshare/manage/folder/dao/FolderRepositoryInsertQueryTest.java
- src/test/java/com/hyun/bookmarkshare/manage/folder/dao/FolderRepositorySelectQueryTest.java
- src/test/java/com/hyun/bookmarkshare/manage/folder/dao/FolderRepositoryUpdateQueryTest.java
Resolves #45 
- folder repository integration Test 수정
- select, update, insert, delete 에 해당하는 각 메서드 Mybatis 통합테스트 수정
- 패키지 전체 테스트 수행 시, primary key auto increment value 으로 인해 발생하는 문제 해결
- 제가 선택한 방법은 각 테스트 마다 `@BeforeEach` 를 통해 auto increment 값을 data.sql 을 참고해 적절한 값으로 변경하는 방식입니다. 더 좋은 테스트 수행 환경 초기화 방식이 있다면 공유부탁드립니다.  
- `@DirtiesContext(classMode = DirtiesContext.ClassMode.BEFORE_CLASS)` 는 각 테스트 클래스 마다 서버를 재 시작하기 때문에 수행시간이 매우 느립니다.
---
> test(folder): Refactor folder repository integration test #45

- src/main/java/com/hyun/bookmarkshare/user/controller/UserPermitRestController.java
- src/main/java/com/hyun/bookmarkshare/user/controller/dto/LoginRequestDto.java
- src/main/java/com/hyun/bookmarkshare/user/dao/UserRepository.java
- src/main/java/com/hyun/bookmarkshare/user/entity/User.java
- src/main/java/com/hyun/bookmarkshare/user/service/UserService.java
- src/main/java/com/hyun/bookmarkshare/user/service/UserServiceImpl.java
- src/main/java/com/hyun/bookmarkshare/user/service/request/LoginServiceRequestDto.java
- src/main/resources/mapper/UserMapper.xml
- src/test/java/com/hyun/bookmarkshare/user/dao/UserRepositoryDeleteQueryTest.java
- src/test/java/com/hyun/bookmarkshare/user/dao/UserRepositoryInsertQueryTest.java
- src/test/java/com/hyun/bookmarkshare/user/dao/UserRepositorySelectQueryTest.java
- src/test/java/com/hyun/bookmarkshare/user/dao/UserRepositoryUpdateQueryTest.java
- src/test/java/com/hyun/bookmarkshare/user/service/UserServiceImplTest.java
Resolves #47 
- User Repository Integration Test 생성
- Mybatis를 활용한 다중 인자 쿼리 메서드를 받기 위해 `@Param` 어노테이션 사용
-
- Mybatis multi params : https://micropilot.tistory.com/2624
---
> test(user): Add user repository integration test #47

- .github/workflows/github-actions-server.yaml
- application.properties 를 생성하는 step 에서 name 이라는 키워드를 추가했었는데, name 은 반드시 하나 이상의 run  또는 uses 가 존재해야 해서 오류가 발생했음.
- 임시적으로 name 의 내용을 주석으로 대체함
- 
- 
---
> chore: delete invalid name in github actions workflow yaml

- .github/workflows/github-actions-server.yaml
> chore: update actions flow yaml change version to 1.0.3

- .github/workflows/github-actions-server.yaml
> github: Merge develop into main

- .github/workflows/github-actions-server.yaml
> chore: Update actions flow yaml delete line 11

- .github/workflows/github-actions-server.yaml
> chore: Update invalid version of actions/checkout@3

- .github/workflows/github-actions-server.yaml
> chore: Update actions workflow line 26 for newline

- .github/workflows/github-actions-server.yaml
```
./gradlew clean build -x test
... 생략 ...
./gradlew: Permission denied
Error: Process completed with exit code 126.
```
- gradlew 권한 부여
- 
- 
---
> chore: Update actions flow yaml add gradle permission

- .github/workflows/github-actions-server.yaml
```
/gradle/wrapper/gradle-wrapper.properties' does not exist.
```
- 
- 
- 
---
> chore: Update actions flow yaml add gradle-wrapper

- .github/workflows/github-actions-server.yaml
- .gitignore
- gradle/wrapper/gradle-wrapper.properties
- gitignore 파일에 gradle-wrapper.properties 파일이 추적제외 처리 되어 있어 Actions 에서 에러가 발생했음.
- `!` 키워드를 통해 해당 파일을 추적제외에서 예외처리 함.
- 
- 
---
> chore: Update gitignore exclude gradle-wrapper.properties

- Dockerfile
> infra: Update symbol for newline

- .github/workflows/github-actions-server.yaml
- Dockerfile
- docker-compose.yaml
> infra: update dockerfile copy

- .github/workflows/github-actions-server.yaml
- nginx 도커파일의 경로를 찾지못하는 문제 발생
- 공식문서를 참고해 해결.
- 
- https://github.com/marketplace/actions/build-and-push-docker-images#git-context
---
> chore: Update nginx dockerfile context path

- .github/workflows/github-actions-server.yaml
> chore: Update actions flow yaml nginx docker file context

- .github/workflows/github-actions-server.yaml
> chore: Update actions flow yaml nginx docker file context using file key

- .github/workflows/github-actions-server.yaml
> chore: Update actions flow yaml change typo

- .github/workflows/github-actions-server.yaml
> chore: Update actions flow yaml change wrong secrets key value

- .github/workflows/github-actions-server.yaml
- docker-compose.yaml
- nginx/conf.d/nginx.conf
- src/main/resources/static/index.html
> chore: Update server_name in nginx.conf

- build.gradle
> chore: Update build gradle for cannot find jdbc driver

- build.gradle
> github: Merge proHyundo_iter4 into main

- build.gradle
> chore: Update build gradle compile to implementation

- build.gradle
> chore: Update build.gradle not found mariadb jdbc driver

- build.gradle
> chore: Update build.gradle and properties to solve load driver

- .github/workflows/github-actions-server.yaml
> chore: Delete gradle cashing steps

- .github/workflows/github-actions-server.yaml
> chore: Update actions flow version to 1.1.1

- .github/workflows/github-actions-server.yaml
> chore: Update actions workflow yaml disable docker image cache

- .github/workflows/github-actions-server.yaml
> chore: Update actions workflow yaml

- docker-compose.yaml
- nginx/conf.d/nginx.conf
> chore: Update nginx.conf and docker compose yaml for ssl

- docker-compose.yaml
- nginx/conf.d/nginx.conf
> chore: Update nginx.conf

- nginx/conf.d/nginx.conf
> chore: Update nginx.conf to recreate nginx docker file

- .github/workflows/github-actions-server.yaml
> chore: Update actions work flow version success ssl certificate

- .github/workflows/github-actions-server.yaml
> chore: Update actions work flow fail start nginx container

- .github/workflows/github-actions-server.yaml
> chore: Update actions work flow add sudo at docker login

- .github/workflows/github-actions-server.yaml
- docker-compose.yaml
> Pro hyundo iter4

- .github/workflows/github-actions-server.yaml
> chore: Update actions workflow change login docker

- .github/workflows/github-actions-server.yaml
> chore: Update actions workflow add docker tags

- .github/workflows/github-actions-server.yaml
> chore: Update actions workflow rollback docker image build and push

- docker-compose.yaml
> chore: Update docker compose yml nginx unless stopped

- docker-compose.yaml
> chore: Update docker compose yml delete certbot restart

- docker-compose.yaml
> chore: Update docker compose yml delete certbot command

- docker-compose.yaml
- nginx/conf.d/nginx.conf
> chore: Update docker compose yml container names

- docker-compose.yaml
> chore: Update docker compose yaml volumes path

- .github/workflows/github-actions-server.yaml
- Dockerfile-nginx
- docker-compose.yaml
> chore: Update docker file nginx change copy path

- nginx/conf.d/default.conf
- nginx/conf.d/nginx.conf
- default.conf 를 찾지못하는 이슈 발생
- default.conf 를 새로 host 위에 생성
- 
- 
---
> chore: Add nginx default.conf v0.0.1

- Dockerfile-nginx
> chore: Update dockerfile-nginx binding path

- Dockerfile-nginx
> chore: Redo dockerfile-nginx copy path

- docker-compose.yaml
> chore: Update docekr compose yaml nginx vlumes host path

- docker-compose.yaml
- nginx/conf.d/default.conf
> chore: Update docker compose yaml volumes mount file

- Dockerfile-nginx
- docker-compose.yaml
> chore: Update dockerfile-nginx and compose yaml

- docker-compose.yaml
> chore: Update docker compose yaml add volume options-nginx.conf

- docker-compose.yaml
> chore: Update docker compose yaml options-ssl-nginx.conf not found

- Dockerfile-nginx
- docker-compose.yaml
> chore: Update docker compose yaml

- Dockerfile-nginx
> chore: Update dockerfile nginx delete COPY

- docker-compose.yaml
> chore: Update docker compose yaml change volumes path

- docker-compose.yaml
> chore: Update docker compose

- docker-compose.yaml
> chore: Update docker compose yaml volumes

- .github/workflows/github-actions-server.yaml
- docker-compose.yaml
> chore: Update use official nginx image instead of custom nginx image

- docker-compose.yaml
> chore: Update docker compose volumes path

- docker-compose.yaml
> chore: Update docker compose yaml volumes from shor to long

- docker-compose.yaml
> chore: Update docker compose yaml volumes path absolute

- .github/workflows/github-actions-server.yaml
> chore: Update docker compose yaml add force image prune

- docker-compose.yaml
> chore: Update docker compose yaml version

- docker-compose.yaml
> chore: Update docker compose yaml delete volume

- .github/workflows/github-actions-server.yaml
- .gitignore
- build.gradle
- docker-compose.yaml
- src/main/java/com/hyun/bookmarkshare/config/WebConfig.java
- src/main/java/com/hyun/bookmarkshare/manage/bookmark/controller/BookmarkRestController.java
- src/main/java/com/hyun/bookmarkshare/security/jwt/filter/JwtAuthenticationFilter.java
- src/main/java/com/hyun/bookmarkshare/security/jwt/util/JwtTokenizer.java
- src/main/java/com/hyun/bookmarkshare/smtp/service/EmailService.java
- src/main/java/com/hyun/bookmarkshare/user/controller/UserPermitRestController.java
- src/main/java/com/hyun/bookmarkshare/user/controller/UserRestController.java
- src/main/java/com/hyun/bookmarkshare/user/service/UserService.java
- src/main/java/com/hyun/bookmarkshare/user/service/UserServiceImpl.java
- src/main/java/com/hyun/bookmarkshare/utils/ApiResponse.java
- src/main/java/com/hyun/bookmarkshare/utils/ApiResponseWithCookie.java
- src/test/java/com/hyun/bookmarkshare/manage/bookmark/controller/BookmarkRestControllerTest.java
- src/test/java/com/hyun/bookmarkshare/manage/folder/controller/FolderRestControllerDocTest.java
- src/test/java/com/hyun/bookmarkshare/smtp/service/EmailServiceTest.java
- src/test/java/com/hyun/bookmarkshare/user/controller/UserPermitRestControllerTest.java
Resolves #146 #147 
- application 설정 파일 properties &rarr; yml 변경
- production, develop profile 분리
- application.properties 를 yml 로 변경.
- git ignore 에 yml 추가.
- yml 로 변경함에 따라 github workflows 의 수정 사항이 발생.
- 확장자 명 변경(properties > yml)
- base64 decode 명령어 추가. (yml 을 base64 으로 인코딩 후 github secrets 에 등록)
- 
- 
---
> Pro hyundo iter5

- .github/workflows/github-actions-server.yaml
> chore(cicd): Update typo error in github actions flow yaml

- .github/workflows/github-actions-server.yaml
- cicd 과정에 mariadb 컨테이너 추가
- 
- 
- 
---
> Merge develop into main: Trial cicd mariadb container add

- .github/workflows/github-actions-server.yaml
- mkdir 명령어를 정상 수행했음에도 다음 run 명령어에서 해당 경로를 찾을 수 없음
- 3개의 파일을 생성 후 업로드 하는 과정을 하나의 명령어로 병합
- 
- 
---
> chore(cicd): Update github actions flow fix no such file issue

- .github/workflows/github-actions-server.yaml
- `log4jdbc.log4j2.properties` 파일을 추가
- `spring.datasource.driver-class-name=net.sf.log4jdbc.sql.jdbcapi.DriverSpy` 설정을 위해 `log4jdbc.log4j2.properties` 파일을 추가하도록 수정
> chore(cicd): Update github actions workflow add lof4j properties

- .github/workflows/github-actions-server.yaml
- src/test/java/com/hyun/bookmarkshare/BookmarkshareApplicationTests.java
- src/test/java/com/hyun/bookmarkshare/utils/DatabaseConnectTest.java
- 데이터베이스 연동 실패
- 데이터베이스 사용자 root 명시
- 깃허브 액션 권한 write-all 부여
> chore(cicd): Update github actions flow mysql user, permission write all

- .github/workflows/github-actions-server.yaml
- src/main/resources/mapper/FolderMapper.xml
- src/main/resources/mapper/ManageMapper.xml
- Github runner's mariadb, test failed issue
- mariadb 연결이 필요한 테스트가 통과되지 않는 이슈를 해결하였습니다.
- /src/main/resources/mapper 의 테이블명을 모두 대문자로 변경
- /src/test/resources 의 data.sql, schema.sql 의 테이블명을 모두 대문자로 변경
> style(mapper): Update all table names lower case to upper case

- .github/workflows/github-actions-server.yaml
- build.gradle
- src/main/java/com/hyun/bookmarkshare/config/StaticResourceConfig.java
- open-api-3.0.1.json 파일을 찾지 못함
- build.gradle 122 라인의 경로에 main이 누락된 것을 추가
- StaticResourceConfig 클래스 파일에 "/api/docs/**" 으로 요청이 올 경우 "classpath:/static/docs/" 에서 찾도록 설정 추가
> docs(api): Update build gradle and static resource config

- .github/workflows/github-actions-server.yaml
- build.gradle
- src/main/java/com/hyun/bookmarkshare/config/SecurityConfig.java
- src/main/java/com/hyun/bookmarkshare/config/StaticResourceConfig.java
- src/main/java/com/hyun/bookmarkshare/developer/controller/DeveloperRestController.java
- src/main/java/com/hyun/bookmarkshare/security/jwt/filter/JwtAuthenticationFilter.java
- swagger-ui 가 필요로 하는 정적 자원 (openapi3.yaml) 을 불러오지 못함
- `build/resources/main/static/docs/` 경로 내부에 `openapi3.yaml` 파일을 복사하도록 설정
- `StaticResourceConfig.java` 에 정적 파일을 응답할 수 있도록 resource handler 설정
> docs(swagger): Try to fix serving openapi3.yaml
